name: form_apps
description: "TaskFlow: a lightweight, local-first, offline task manager with profile-based task lists and custom groups."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#006C67"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  min_sdk_android: 21
