class AppTranslations {
  const AppTranslations._();

  static const Map<String, String> _values = {
    'login_title': 'Sign in',
    'username': 'Username',
    'username_empty': 'Username cannot be empty.',
    'password': 'Password',
    'password_empty': 'Password cannot be empty.',
    'password_short': 'Password must be at least 6 characters.',
    'login_button': 'Sign in',
    'no_account': 'No account yet?',
    'register_now': 'Create account',
    'invalid_credentials': 'Invalid username or password.',
    'register_title': 'Create account',
    'register_button': 'Create account',
    'already_have_account': 'Already have an account?',
    'login_now': 'Sign in',
    'register_success': 'Account created successfully.',
    'register_failed': 'That username is already in use.',
    'task_list_title': 'TaskFlow',
    'pending_tasks': 'Open',
    'completed_tasks': 'Completed',
    'no_completed_tasks': 'No completed tasks yet.',
    'no_pending_tasks': 'No open tasks in this group.',
    'add_task': 'Add task',
    'dark_mode': 'Dark mode',
    'logout': 'Sign out',
    'delete_account': 'Delete account',
    'add_task_title': 'New task',
    'task_name': 'Task name',
    'task_desc': 'Description',
    'group': 'Group',
    'add_new_group': 'New group',
    'cancel': 'Cancel',
    'add': 'Add',
    'success': 'Success',
    'task_added_success': 'Task added.',
    'ok': 'OK',
    'new_group_title': 'Create group',
    'group_name': 'Group name',
    'no_details': 'No description.',
    'created_at': 'Created',
    'completed_at': 'Completed',
    'delete': 'Delete',
    'close': 'Close',
    'group_general': 'General',
    'group_home': 'Home',
    'group_work': 'Work',
    'group_school': 'School',
    'welcome': 'Welcome, ',
    'enter_password_to_continue': 'Enter your password to continue.',
    'who_is_logging_in': 'Choose a profile',
    'add_account': 'Add profile',
    'wrong_password': 'Incorrect password.',
    'join_us_info': 'Create a local profile to get started.',
    'please_enter_username': 'Enter a username.',
    'username_short': 'Username must be at least 3 characters.',
    'please_enter_password': 'Enter a password.',
    'all_tasks': 'All tasks',
    'update': 'Save changes',
    'delete_group_title': 'Delete group',
    'delete_group_desc': 'Tasks in this group will move to General.',
    'yes': 'Delete',
    'forgot_password': 'Forgot password?',
    'reset_password_title': 'Reset password',
    'reset_password_desc': 'Set a new password for this profile.',
    'new_password': 'New password',
    'confirm_new_password': 'Confirm new password',
    'passwords_do_not_match': 'Passwords do not match.',
    'password_reset_success': 'Password updated. You can sign in now.',
    'reset_password_button': 'Reset password',
  };

  static String getText(String _, String key) => _values[key] ?? key;
}
